//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CM_APPLICATIONS
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class COPR16_RTVALUE_TR
    {

        [DisplayName("RTV_ID")]
        public string RTV_ID { get; set; }

        [DisplayName("RTV_NAME")]
        public string RTV_NAME { get; set; }

        [DisplayName("CREATED DATE")]
        public Nullable<System.DateTime> ADATE { get; set; }

        [DisplayName("CREATED BY")]
        public string CRE_BY { get; set; }

        [DisplayName("MODIFIED BY")]
        public string MOD_BY { get; set; }

        [DisplayName("MODIFIED DATE")]
        public Nullable<System.DateTime> MOD_DATE { get; set; }

        [DisplayName("RETURN TYPE ID")]
        public string RTYPE_ID { get; set; }

        [DisplayName("MACHINE ID")]
        public string MANC_ID { get; set; }

        [DisplayName("DEF_VALUE")]
        public string DEF_VALUE { get; set; }
    }
}
