//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CM_APPLICATIONS
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class COPR16_STEP_MSTR
    {

        [DisplayName("STEP ID")]
        public string STEP_ID { get; set; }

        [DisplayName("STEP NAME")]
        public string STEP_NAME { get; set; }

        [DisplayName("STEP DESCRIPTION")]
        public string STEP_DESC { get; set; }

        [DisplayName("CREATED DATE")]
        public Nullable<System.DateTime> ADATE { get; set; }

        [DisplayName("CREATED BY")]
        public string CRE_BY { get; set; }

        [DisplayName("MODIFIED BY")]
        public string MOD_BY { get; set; }

        [DisplayName("MODIFIED DATE")]
        public Nullable<System.DateTime> NOD_DATE { get; set; }

        [DisplayName("ACTIVE")]
        public Nullable<bool> FLGACT { get; set; }

        [DisplayName("MANC_ID")]
        public string MANC_ID { get; set; }

        [DisplayName("RTV_ID")]
        public string RTV_ID { get; set; }

        [DisplayName("GRPT_ID")]
        public string GRPT_ID { get; set; }

        [DisplayName("SGRPT_ID")]
        public string SGRPT_ID { get; set; }
    }
}
