//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CM_APPLICATIONS
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class COPR16_WORKFLOW_DT
    {

        [DisplayName("PROCESS TEST DETAIL ID")]
        public string WRKD_ID { get; set; }

        [DisplayName("PROCESS TEST DETAIL DESCRIPTION")]
        public string WRKD_DESC { get; set; }

        [DisplayName("PROCESS TEST ID")]
        public string WRK_ID { get; set; }

        [DisplayName("STEP ID")]
        public string STEP_ID { get; set; }

        [DisplayName("PARALLEL TEST (Y/N)")]
        public Nullable<bool> WRKD_PARL { get; set; }

        [DisplayName("WRKD_ANDCOND")]
        public Nullable<bool> WRKD_ANDCOND { get; set; }

        [DisplayName("CREATED DATE")]
        public Nullable<System.DateTime> ADATE { get; set; }

        [DisplayName("CREATED BY")]
        public string CRE_BY { get; set; }

        [DisplayName("MODIFIED DATE")]
        public Nullable<System.DateTime> MOD_DATE { get; set; }

        [DisplayName("MODIFIED BY")]
        public string MOD_BY { get; set; }

        [DisplayName("WRKD_WITH_ID")]
        public string WRKD_WITH_ID { get; set; }

        [DisplayName("WRKD_SEQ")]
        public string WRKD_SEQ { get; set; }

        [DisplayName("WRKD_MAIN")]
        public Nullable<bool> WRKD_MAIN { get; set; }

        [DisplayName("WRKD_ORDER")]
        public string WRKD_ORDER { get; set; }
    }
}
