//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CM_APPLICATIONS
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class COPR16_STD_MSTR
    {

        [DisplayName("STANDARD ID")]
        public string STD_ID { get; set; }

        [DisplayName("STANDARD NAME")]
        public string STD_NAME { get; set; }

        [DisplayName("STANDARD DESCRIPTION")]
        public string STD_DESC { get; set; }

        [DisplayName("CREATED DATE")]
        public System.DateTime ADATE { get; set; }

        [DisplayName("CREATED BY")]
        public string CRE_BY { get; set; }

        [DisplayName("MODIFIED BY")]
        public string MOD_BY { get; set; }

        [DisplayName("MODIFIED DATE")]
        public Nullable<System.DateTime> NOD_DATE { get; set; }

        [DisplayName("ACTIVE")]
        public Nullable<bool> FLGACT { get; set; }

        [DisplayName("FUNCTION INTERFACE ID")]
        public string PROC_ID { get; set; }

        [DisplayName("REGULATORY ID")]
        public string STDREG_ID { get; set; }
    }
}
