//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CM_APPLICATIONS
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class COPR16_STDDET
    {

        [DisplayName("STDD_ID")]
        public string STDD_ID { get; set; }

        [DisplayName("STD_ID")]
        public string STD_ID { get; set; }

        [DisplayName("STDD_NAME")]
        public string STDD_NAME { get; set; }

        [DisplayName("STDD_DESC")]
        public string STDD_DESC { get; set; }

        [DisplayName("PRROC_ID")]
        public string PRROC_ID { get; set; }

        [DisplayName("CREATED DATE")]
        public Nullable<System.DateTime> ADATE { get; set; }

        [DisplayName("CREATED BY")]
        public string CRE_BY { get; set; }

        [DisplayName("MODIFIED BY")]
        public string MOD_BY { get; set; }

        [DisplayName("MODIFIED DATE")]
        public Nullable<System.DateTime> NOD_DATE { get; set; }

        [DisplayName("ACTIVE")]
        public Nullable<bool> FLGACT { get; set; }

        [DisplayName("NO.")]
        public Nullable<decimal> SEQ_NO { get; set; }

        [DisplayName("STPE ID")]
        public string STEP_ID { get; set; }
    }
}
