//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CM_APPLICATIONS
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class COPR16_REPORT
    {

        [DisplayName("STANDARD ID")]
        public string STD_ID { get; set; }

        [DisplayName("MODEL ID")]
        public string MODEL_ID { get; set; }

        [DisplayName("ITEM ID")]
        public string ITEM_ID { get; set; }

        [DisplayName("COP RUNNING NO.")]
        public string COP_ID { get; set; }

        [DisplayName("FUNCTION INTERFACE ID")]
        public string PROC_ID { get; set; }

        [DisplayName("SUMMARY BY")]
        public string SUM_BY { get; set; }

        [DisplayName("APPROVED BY")]
        public string APP_BY { get; set; }

        [DisplayName("CREATED DATE")]
        public System.DateTime ADATE { get; set; }
    }
}
