//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CM_APPLICATIONS
{
    using System;
    using System.Collections.Generic;
    
    public partial class COPR16_IMPORT_CONTENTS
    {
        public string FSIM_UNIQ_ID { get; set; }
        public string ITEM_ID { get; set; }
        public string QTY { get; set; }
        public string CRE_BY { get; set; }
    }
}
