//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CM_APPLICATIONS
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class COPR16_FILE_IMPORT
    {
        [DisplayName("UPLOAD DATE : ")]
        public Nullable<System.DateTime> FSIM_DT { get; set; }
        [DisplayName("FILE NAME : ")]
        public string FSIM_NAME { get; set; }
        [DisplayName("FILE EXT. : ")]
        public string FSIM_EXT { get; set; }
        [DisplayName("FILE PATH. : ")]
        public string FSIM_PATH { get; set; }
        [DisplayName("FILE SIZE. : ")]
        public string FSIM_SIZE { get; set; }
        [DisplayName("FILE FORMAT. : ")]
        public string FSIM_FORMAT { get; set; }
        public string FSIM_UNIQ_ID { get; set; }
        [DisplayName("CREATE BY : ")]
        public string CRE_BY { get; set; }
        [DisplayName("FILE DATE . : ")]
        public string FSIM_SEQDT { get; set; }
    }
}
