//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CM_APPLICATIONS
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class COPR16_MACHINE_MSTR
    {

        [DisplayName("MACHINE ID")]
        public string MANC_ID { get; set; }

        [DisplayName("MACHINE DESCRIPTION")]
        public string MANC_DESC { get; set; }

        [DisplayName("MACHINE TYPE ID")]
        public string MTYPE_ID { get; set; }

        [DisplayName("CREATED DATE")]
        public Nullable<System.DateTime> ADATE { get; set; }

        [DisplayName("CREATED BY")]
        public string CRE_BY { get; set; }

        [DisplayName("MODIFIED BY")]
        public string MOD_BY { get; set; }

        [DisplayName("MODIFIED DATE")]
        public Nullable<System.DateTime> MOD_DATE { get; set; }

        [DisplayName("IP ADDRESS")]
        public string IPADDR { get; set; }

        [DisplayName("SUBNET")]
        public string SUBNET { get; set; }

        [DisplayName("GATEWAY")]
        public string GATEWAY { get; set; }

        [DisplayName("USERNAME")]
        public string USERNAME { get; set; }

        [DisplayName("PASSWORD")]
        public string PASSWORD { get; set; }

        [DisplayName("HOME_PATH")]
        public string HOME_PATH { get; set; }

        [DisplayName("SUB_PATH")]
        public string SUB_PATH { get; set; }

        [DisplayName("FILE NAME")]
        public string FILENAME { get; set; }

        [DisplayName("MULTIPLE USE")]
        public Nullable<bool> FLGACT { get; set; }
    }
}
