//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CM_APPLICATIONS
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class COPR16_RTDT_MSTR
    {

        [DisplayName("RETURN TYPE ID")]
        public string RTTYPE_ID { get; set; }

        [DisplayName("RTDT_ID")]
        public string RTDT_ID { get; set; }

        [DisplayName("RTDT_NAME")]
        public string RTDT_NAME { get; set; }

        [DisplayName("MSTYPE_ID")]
        public string MSTYPE_ID { get; set; }

        [DisplayName("REF_ID")]
        public string REF_ID { get; set; }

        [DisplayName("ACTIVE")]
        public Nullable<bool> FLGACT { get; set; }

        [DisplayName("CREATED DATE")]
        public Nullable<System.DateTime> ADATE { get; set; }

        [DisplayName("CREATED BY")]
        public string CRE_BY { get; set; }

        [DisplayName("MODIFIED DATE")]
        public Nullable<System.DateTime> MOD_DATE { get; set; }

        [DisplayName("MODIFIED BY")]
        public string MOD_BY { get; set; }
    }
}
