//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CM_APPLICATIONS
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class COPR16_COPRUNNING_RT
    {
        [DisplayName("COP RUNNING NO.")]
        public string COPR_ID { get; set; }

        [DisplayName("FG NO.")]
        public string PNO { get; set; }

        [DisplayName("FG TYPE")]
        public string FGTYPE_ID { get; set; }

        [DisplayName("PROCESS TEST ID")]
        public string WRK_ID { get; set; }

        [DisplayName("PROCESS TEST ID")]
        public string WRKD_ID { get; set; }

        [DisplayName("MACHINE TYPE ID")]
        public string MACHINETYPE_ID { get; set; }

        [DisplayName("RETURN TYPE ID")]
        public string RETURNTYPE_ID { get; set; }

        [DisplayName("VALUE")]
        public string VALUE { get; set; }

        [DisplayName("STATUS ID")]
        public string STATUS_ID { get; set; }

        [DisplayName("TEST START DATE")]
        public Nullable<System.DateTime> TEST_START { get; set; }

        [DisplayName("TEST FINISH DATE")]
        public Nullable<System.DateTime> TEST_FINISH { get; set; }

        [DisplayName("TEST BY")]
        public string TEST_BY { get; set; }

        [DisplayName("REV")]
        public string REV { get; set; }

        [DisplayName("SEQ_NO")]
        public string SEQ_NO { get; set; }

        [DisplayName("MACHINE ID")]
        public string MACHINE_ID { get; set; }

        [DisplayName("CLOSED BY")]
        public string CLOSE_BY { get; set; }

        [DisplayName("MANSUREMENT ID")]
        public string RTDT_ID { get; set; }

        [DisplayName("MANSUREMENT NAME")]
        public string RTDT_NAME { get; set; }

        [DisplayName("UNIT NAME/REF.")]
        public string RTDT_REF_ID { get; set; }
    }
}
