//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CM_APPLICATIONS
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class COPR16_ITEMS_VOLUME
    {

        [DisplayName("RUNNING_ID")]
        public System.Guid RUNNING_ID { get; set; }

        [DisplayName("FG NO. (BUCKLE)")]
        public string ITEM_ID { get; set; }

        [DisplayName("BUSINESS DATE")]
        public Nullable<System.DateTime> BUSI_DATE { get; set; }

        [DisplayName("QUANTITY")]
        public Nullable<decimal> QTY { get; set; }
    }
}
