//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CM_APPLICATIONS
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class COPR16_FGTEST
    {

        [DisplayName("FG NO.")]
        public string FGTEST_ID { get; set; }

        [DisplayName("MODEL ID")]
        public string MODEL_ID { get; set; }

        [DisplayName("POSITION ID")]
        public string POS_ID { get; set; }

        [DisplayName("FG NO. (BUCKLE)")]
        public string ITEM_ID { get; set; }

        [DisplayName("FGT_ID")]
        public string FGT_ID { get; set; }

        [DisplayName("SERIAL NO.")]
        public string SN { get; set; }

        [DisplayName("COP RUNNING NO.")]
        public string COPR_ID { get; set; }

        [DisplayName("FGTD_ID")]
        public string FGTD_ID { get; set; }
    }
}
