//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CM_APPLICATIONS
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class COPR16_COPRUNNING_DT
    {
        [DisplayName("COP RUNNING NO.")]
        public string COPR_ID { get; set; }

        [DisplayName("FG TYPE ID")]
        public string FGTYPE_ID { get; set; }

        [DisplayName("FG NO.")]
        public string PNO { get; set; }

        [DisplayName("LOT NO.")]
        public string LOTNO { get; set; }

        [DisplayName("DESCRIPTION")]
        public string DESC { get; set; }
    }
}
