//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CM_APPLICATIONS
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class COPR16_MANCTYPE_MSTR
    {
        [DisplayName("MACHINE TYPE ID")]
        public string MTYPE_ID { get; set; }

        [DisplayName("MACHINE TYPE NAME")]
        public string MTYPE_NAME { get; set; }

        [DisplayName("CREATED DATE")]
        public Nullable<System.DateTime> ADATE { get; set; }

        [DisplayName("CREATED BY")]
        public string CRE_BY { get; set; }

        [DisplayName("MODIFIED BY")]
        public string MOD_BY { get; set; }

        [DisplayName("MODIFIED DATE")]
        public Nullable<System.DateTime> MOD_DATE { get; set; }

        [DisplayName("ACTIVE")]
        public Nullable<bool> FLGACT { get; set; }

        [DisplayName("MACHINE TYPE DESCRIPTION")]
        public string DESC { get; set; }

        [DisplayName("ACTIVE")]
        public string FGT_ID { get; set; }

        [DisplayName("ONLINE (Y/N)")]
        public Nullable<bool> FLGONLINE { get; set; }

        [DisplayName("RETURN TYPE ID")]
        public string RTYPE_ID { get; set; }
    }
}
