//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CM_APPLICATIONS
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class COPR16_SUBGRPTEST_MSTR
    {

        [DisplayName("XXX")]
        public string SGRPT_ID { get; set; }

        [DisplayName("XXX")]
        public string SGRPT_NAME { get; set; }

        [DisplayName("XXX")]
        public string SGRPT_DESC { get; set; }

        [DisplayName("XXX")]
        public Nullable<System.DateTime> ADATE { get; set; }

        [DisplayName("XXX")]
        public string CRE_BY { get; set; }

        [DisplayName("XXX")]
        public string MOD_BY { get; set; }

        [DisplayName("XXX")]
        public Nullable<System.DateTime> NOD_DATE { get; set; }

        [DisplayName("XXX")]
        public Nullable<bool> FLGACT { get; set; }
    }
}
